import type { Metadata } from "next";
import { montserrat } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import NavigationProvider from "./ui/components/navigationProvider";

export const metadata: Metadata = {
  title: "Infinity Pritty Jewellery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* TODO: nanti coba ganti ke favicon */}
        <link rel="icon" href="/imgs/logo-purple.png" type="image/png" sizes="16x16 32x32" />
      </head>
      <body className={`${montserrat.className} antialiased`} >
        <NavigationProvider>{children}</NavigationProvider>
      </body>
    </html>
  );
}

